version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:14.18.1

jobs:
  deploy:
    executor: my-custom-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies- # Fallback cache
      - run: |
          npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Deploying
          command: |
            echo $SERVICE_ACCOUNT | base64 -d >> service_account.json
            export NODE_ENV=production
            npm run build
            ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
      - store_artifacts:
          path: nextjs
          destination: nextjs

workflows:
  deploy:
    jobs:
      - deploy
