version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:14.18.1

jobs:
  deploy:
    executor: my-custom-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies- # Fallback cache
      - run: |
          npm install
          npm install -g firebase-tools
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: |
          echo $SERVICE_ACCOUNT | base64 -d >> service_account.json
          npm run build
          firebase deploy --token "$FIREBASE_TOKEN" -P "default" --only "function:nextjs,hosting"

      - store_artifacts:
          path: nextjs
          destination: nextjs

workflows:
  deploy:
    jobs:
      - deploy
