version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:14.18.1

jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies- # Fallback cache
      - run: |
          npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: |
          echo $SERVICE_ACCOUNT | base64 -d >> service_account.json
          npm run build
  deploy:
    executor: my-custom-executor
    steps:
      - run: |
          cat nextjs
workflows:
  my-custom-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
