version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:14.18.1

jobs:
  my-job-name:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm run build

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
